name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Check types
        run: yarn check
      - name: Bundle up
        run: yarn build
        env:
          VITE_GTAG_ID: 'G-58W6EWVQZW'
      - name: Move 404 route
        run: mv "./build/404/index.html" ./build/404.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
